### PR TITLE
Python 3 support

### PR DESCRIPTION
**Pull request by prabeesh**
not tested for anchor text

### CODE REVIEW

**Comment by b4hand** [comment]
In the future, we would prefer formatting changes to be separate from functional changes.

**Comment by b4hand** [comment]
I'm going to try to confirm the anchor text changes before merging.

**Comment by b4hand** [comment]
There's at least one bug. I get an exception `TypeError: the JSON object must be str, not 'bytes'` from this line in the `example.py`:
```python
l.urlMetrics(['www.moz.com', 'www.moz.com/blog'])
```
However, I have figured out the fix, and it is a small change, so I'll go ahead and merge this branch since it's easier for me to just fix it.

**Comment by prabeesh** [comment]
@b4hand If possible please mention Python 3 support in the READ me file.

**Comment by b4hand** [comment]
A comment has been added.

**Pull request merged**
